on:
  push:
    branches:
      - main
  pull_request:

name: Continuous Integration

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.60.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - run: sudo apt-get install -y libfontconfig-dev pkgconf

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  aur_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate pkgver
        run: |
          echo "pkgver=$(git rev-list --count HEAD).$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Generate PKGBUILD
        env:
          PKGVER: ${ env.pkgver }
        run: ./ci/generate-pkgbuild.py3

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.5.0
        with:
          pkgname: kickoff-git
          pkgbuild: ./pkgbuild/kickoff-git/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
